### ISSUE TITLE
spin and pulse not work

### ISSUE THREAD

**Issue by qmhc** [Justineo/vue-awesome#165]
register

```js
import 'vue-awesome/icons/spinner'

import Vue from 'vue'
import Icon from 'vue-awesome/components/Icon'

Vue.component('Icon', Icon)
```

use

```html
<Icon pulse name="spinner"></Icon>
```

but not work, `spin` is also

I see the code in `Icon.vue`

```css
.fa-spin > g {
  animation: fa-spin 1s 0s infinite linear;
}

.fa-pulse > g {
  animation: fa-spin 1s infinite steps(8);
}
```

but in my rendered HTML

```html
<svg aria-hidden="true" width="16" height="16" viewBox="0 0 512 512" focusable="false" class="fa-icon fa-spin fa-pulse"><path d="M304 48c0 26.5-21.5 48-48 48s-48-21.5-48-48 21.5-48 48-48 48 21.5 48 48zM256 416c26.5 0 48 21.5 48 48s-21.5 48-48 48-48-21.5-48-48 21.5-48 48-48zM464 208c26.5 0 48 21.5 48 48s-21.5 48-48 48-48-21.5-48-48 21.5-48 48-48zM96 256c0 26.5-21.5 48-48 48s-48-21.5-48-48 21.5-48 48-48 48 21.5 48 48zM108.9 355.1c26.5 0 48 21.5 48 48 0 26.5-21.5 48-48 48s-48-21.5-48-48 21.5-48 48-48zM403.1 355.1c26.5 0 48 21.5 48 48 0 26.5-21.5 48-48 48s-48-21.5-48-48 21.5-48 48-48zM108.9 60.9c26.5 0 48 21.5 48 48s-21.5 48-48 48-48-21.5-48-48 21.5-48 48-48z"></path></svg>
```

without `<g>`

>version: "^4.0.2"
