### ISSUE TITLE
how to add the fa-fw class to the icons?

### ISSUE THREAD

**Issue by zassq** [Justineo/vue-awesome#37]
Hi great component, just wondering how to add the fixed width class 'fa-fw' to it?
Is it possible?
Thanks.

**Comment by Justineo** [comment]
You can set the width of the icon with CSS directly like this:

```css
.fa-icon {
  width: 32px;
}
```
