### ISSUE TITLE
Safari: CSS height and width css does not work

### ISSUE THREAD

**Issue by pixelbacon** [Justineo/vue-awesome#57]
Check https://justineo.github.io/vue-awesome/demo/ in Safari (Desktop and Mobile). Changing them via CSS does not seem to work.

**Comment by Justineo** [comment]
How did you change them via CSS exactly?

**Comment by pixelbacon** [comment]
Per the readme. Including trying to edit them in Safari (desktop) Developer Mode. No dice.

```CSS
.fa-icon {
  width: auto;
  height: 1em; /* or any other relative font sizes */
}
```

BTW: This is an awesome component and the work is greatly appreciated :)

**Comment by Justineo** [comment]
@pixelbacon Thanks! I can see the problem, but I haven't found a workaround yet.

**Comment by Justineo** [comment]
```css
.fa-icon {
  width: auto;
  height: 1em; /* or any other relative font sizes */

  max-width: 100%;
  max-height: 100%;
}
```

@pixelbacon I found that adding `max-width` and `max-height` may work this around for Safari.
