### ISSUE TITLE
Support for Font Awesome formatting classes beyond what's shown on the demo page

### ISSUE THREAD

**Issue by ergh99** [Justineo/vue-awesome#60]
Specifically, does Vue-Awesome support fa-fw (fixed width) somehow?  I'm new to FA and enjoying VA very much :)

**Comment by Justineo** [comment]
You can just do this:

```css
.fa-icon {
  width: 16px; /* or other fixed length value */
}
```
